export type ViewType =
  | 'dashboard'
  | 'profile'
  | 'employees'
  | 'attendance'
  | 'attendance-reports'
  | 'leave-management'
  | 'payroll'
  | 'productivity'
  | 'documents'
  | 'settings'
  | 'team' 